import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" translate="no" suppressHydrationWarning>
      <body
        className={`${nunito.variable} bg-white text-[#121212] antialiased`}>
        <Navbar />
        <div className="w-full px-2 md:px-12 lg:px-16 xl:px-24 2xl:px-32 ">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
